apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::404097363077:role/UdacityFlaskDeployCBKubectlRole
      username: build      
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::404097363077:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-17C402QC9VF6L
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-05-31T05:32:12Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "23462"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 744d3303-4df8-48f7-9927-985d7b2e55f6
